name: seaice-cdr-ncai 
channels:
  - conda-forge
  - nodefaults

dependencies:
  - python ~=3.11.7

  - aiohttp
  - h5netcdf
  - fsspec
  - netcdf4
  - numpy
  - pandas
  - pre-commit
  - pystac
  - pathlib
  - xarray
  - matplotlib

  # jupyter environment
  - notebook
  - jupyterlab
